# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1507028644);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1507028764);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1507029124);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1507028522);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1507029004);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1507028402);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1507029244);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1507028884);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1506096380);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migrated-sync-button", true);
user_pref("browser.migration.version", 47);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.shieldstudy.enabled", false);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1507028430110");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1507030115110");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1507028430836");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1507032030836");
user_pref("browser.search.countryCode", "TW");
user_pref("browser.search.region", "TW");
user_pref("browser.slowStartup.averageTime", 52678);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20170816210634");
user_pref("browser.startup.homepage_override.mstone", "55.0.2");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\",\"webide-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20170926);
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1506096456214");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("e10s.rollout.cohort", "addons-set50allmpc-test");
user_pref("e10s.rollout.cohortSample", "0.637766");
user_pref("e10s.rollout.cohortSample.multi", "0.006028");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 21);
user_pref("extensions.e10s.rollout.blocklist", "");
user_pref("extensions.e10s.rollout.hasAddon", true);
user_pref("extensions.e10s.rollout.policy", "50allmpc");
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.e10sMultiBlockedByAddons", true);
user_pref("extensions.getAddons.cache.lastUpdate", 1507028646);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20170302.01");
user_pref("extensions.lastAppVersion", "55.0.2");
user_pref("extensions.lastPlatformVersion", "55.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-recipe-client.api_url", "https://normandy.cdn.mozilla.net/api/v1");
user_pref("extensions.shield-recipe-client.dev_mode", false);
user_pref("extensions.shield-recipe-client.enabled", true);
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.logging.level", 50);
user_pref("extensions.shield-recipe-client.run_interval_seconds", 86400);
user_pref("extensions.shield-recipe-client.startup_delay_seconds", 300);
user_pref("extensions.shield-recipe-client.user_id", "425f9900-4346-444f-bdcb-eef48b8d6a51");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{1457c516-a441-4e63-b5a9-e0702f85e6b4}\",\"addons\":{\"clicktoplay-rollout@mozilla.org\":{\"version\":\"1.4\"},\"e10srollout@mozilla.org\":{\"version\":\"2.05\"},\"followonsearch@mozilla.com\":{\"version\":\"0.9.4\"},\"onboarding@mozilla.org\":{\"version\":\"0.1\"},\"screenshots@mozilla.org\":{\"version\":\"10.12.0\"}}}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1507029474);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1506096458);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20170816210634");
user_pref("media.gmp-manager.lastCheck", 1507028388);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 67916);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugins.ctprollout.cohort", "user-changed-from-test");
user_pref("plugins.ctprollout.cohortSample", "0.365550");
user_pref("services.blocklist.clock_skew_seconds", 151);
user_pref("services.blocklist.gfx.checked", 1507028612);
user_pref("services.blocklist.last_update_seconds", 1507028612);
user_pref("services.blocklist.onecrl.checked", 1507028612);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1507028340);
user_pref("toolkit.telemetry.cachedClientID", "77adaae1-1505-47e8-8d59-d5159b7b0481");
user_pref("toolkit.telemetry.previousBuildID", "20170816210634");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
